name: Setup JDK 11
description: Setup JDK 11

inputs:
  gpg-secret-key:
    description: The gpg secret key
    default: ''
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v3
      if: env.JAVA_IS_SETUP != 'true'
      with:
        java-version: "11"
        distribution: "temurin"
        server-id: ossrh
        server-username: MAVEN_CENTRAL_USERNAME
        server-password: MAVEN_CENTRAL_PASSWORD
        gpg-private-key: ${{ inputs.gpg-secret-key }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        cache: maven
    - id: set_JAVA_IS_SETUP_var
      shell: bash
      run: |
        echo "JAVA_IS_SETUP=true" >> $GITHUB_ENV
