name: Setup needed environment variables
description: Setup needed environment variables

runs:
  using: composite
  steps:
    - name: Determine ccache variant
      shell: bash
      run: |
        echo "CMAKE_CXX_COMPILER_LAUNCHER=${{ ( (runner.os == 'Windows') && 'sccache' ) || 'ccache' }}"                             >> $GITHUB_ENV

    - name: Setup Homebrew on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin"                                                       >> $GITHUB_PATH

    - name: Setup build variables on macOs
      if: runner.os == 'macOs'
      shell: bash
      run: |
        echo "CXXFLAGS=-stdlib=libc++"                                                                                              >> $GITHUB_ENV

    - name: Setup BOOST_ROOT and directories on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Write "BOOST_DOWNLOAD_URI=https://boostorg.jfrog.io/artifactory/main/release/1.81.0/binaries/boost_1_81_0-msvc-14.3-64.exe" >> $env:GITHUB_ENV
        Write "BOOST_INSTALLER_PATH=$env:TEMP\boost.exe"                                                                            >> $env:GITHUB_ENV
        Write "BOOST_ROOT=$env:TEMP\boost"                                                                                          >> $env:GITHUB_ENV
