name: Build native library for the runner
description: Build native library for the runner

inputs:
  upload-path:
    description: The path where to find the native library to upload
    default: ''
    required: false

runs:
  using: composite
  steps:
    - uses: ./.github/actions/build_native_library/env_variables

    - uses: ./.github/actions/build_native_library/setup

    - name: Build
      shell: bash
      run: |
        cmake --version
        cmake --preset release -L
        cmake --build --preset release --verbose

    - name: Upload native library
      if: ${{ inputs.upload-path != '' }}
      uses: actions/upload-artifact@v3
      with:
        name: native-library-${{ runner.os }}
        path: ${{ inputs.upload-path }}
        retention-days: 1
