name: Build the QuantLib maven artefact

on:
    workflow_dispatch: {}

env:
  QUANTLIB_VERSION:                 "1.29.0"
  MAVEN_PATH:                       maven
  MAVEN_TARGET_PATH:                maven/target
  MAVEN_RESOURCES_NATIVE_LIBS_PATH: maven/src/main/resources/native

jobs:
    build-on-macos:
      runs-on: macos-12
      steps:
        - uses: actions/checkout@v3
          with: 
            submodules: 'true'

        - name: Build native library for ${{ runner.os }}
          uses: ./.github/actions/build_native_library
    
    build-on-windows:
      runs-on: windows-2022
      steps:
          - uses: actions/checkout@v3
            with: 
              submodules: 'true'
  
          - name: Build native library for ${{ runner.os }}
            uses: ./.github/actions/build_native_library
    
    create-quantlib-jar-on-linux:
      runs-on: ubuntu-22.04
      needs: [ build-on-macos, build-on-windows ]
      steps:
        - uses: actions/checkout@v3
          with: 
            submodules: 'true'

        - name: Download macOS native library
          uses: actions/download-artifact@v3
          with:
            name: native-library-macOS
            path: ${{ env.MAVEN_RESOURCES_NATIVE_LIBS_PATH }}
            
        - name: Download Windows native library
          uses: actions/download-artifact@v3
          with:
            name: native-library-Windows
            path: ${{ env.MAVEN_RESOURCES_NATIVE_LIBS_PATH }}

        - name: Build native library for ${{ runner.os }}
          uses: ./.github/actions/build_native_library

        - name: Upload jars
          uses: actions/upload-artifact@v3
          with:
            name: QuantLib.jars
            path: ${{ env.MAVEN_TARGET_PATH }}/quantlib-*.jar
